"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import json
from pathlib import Path
import hashlib

from loguru import logger

def stone(totient, base, location):
    res = base
    for _ in range(location):
        res *= res
        res %= totient
    return res 

def wind(key, distance, exponent, modulus, totient):
    # First, we generate the exponent to the key.
    key_exp = 1
    bit_position = 0
    bit = 1
    while bit <= distance:
        if bit & distance > 0:
            key_exp *= stone(totient, exponent, bit_position)
            key_exp %= totient
        bit *= 2
        bit_position += 1
    # Then, we just return the power.
    return pow(key, key_exp, modulus)

def pack_stones(stones):
    res = b""
    for stone in stones:
        res += stone.to_bytes(64, byteorder="big")
    return res

def gen_subscription(
    secrets: bytes, device_id: int, start: int, end: int, channel: int
) -> bytes:
    """Generate the contents of a subscription.

    The output of this will be passed to the Decoder using ectf25.tv.subscribe

    :param secrets: Contents of the secrets file generated by ectf25_design.gen_secrets
    :param device_id: Device ID of the Decoder
    :param start: First timestamp the subscription is valid for
    :param end: Last timestamp the subscription is valid for
    :param channel: Channel to enable
    """
    secrets = json.loads(secrets)

    modulus = secrets["modulus"]
    totient = secrets["totient"]
    exponent = secrets["exponent"]

    forward = secrets["sub" + channel]["forward"]
    backward = secrets["sub" + channel]["backward"]

    b_root = 2 ** 64 - 1
    b_dist = b_root - end

    # First, we should make the stepping stones using the totient.

    stones = []
    for l in range(4, 64, 4):
        stones.append(stone(totient, exponent, l))


    # Now, we wind forward the root keys to the correct position.
    f = wind(forward, start, exponent, modulus, totient)
    b = wind(backward, b_dist, exponent, modulus, totient)

    h_id = sha3_512(device_id)
    b_hashed = b ^ h_id
    # Finally, we pack this like follows:
    
    # Pack the subscription. This will be sent to the decoder with ectf25.tv.subscribe
    return f.to_bytes(64, byteorder='big') + b_hashed.to_bytes(64, byteorder='big') + \
        modulus.to_bytes(64, byteorder='big') + pack_stones(stones) + channel.to_bytes(4, byteorder='big') + \
        start.to_bytes(8, byteorder='big') + end.to_bytes(8, byteorder='big')

def parse_args():
    """Define and parse the command line arguments

    NOTE: Your design must not change this function
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Force creation of subscription file, overwriting existing file",
    )
    parser.add_argument(
        "secrets_file",
        type=argparse.FileType("rb"),
        help="Path to the secrets file created by ectf25_design.gen_secrets",
    )
    parser.add_argument("subscription_file", type=Path, help="Subscription output")
    parser.add_argument(
        "device_id", type=lambda x: int(x, 0), help="Device ID of the update recipient."
    )
    parser.add_argument(
        "start", type=lambda x: int(x, 0), help="Subscription start timestamp"
    )
    parser.add_argument("end", type=int, help="Subscription end timestamp")
    parser.add_argument("channel", type=int, help="Channel to subscribe to")
    return parser.parse_args()


def main():
    """Main function of gen_subscription

    You will likely not have to change this function
    """
    # Parse the command line arguments
    args = parse_args()

    subscription = gen_subscription(
        args.secrets_file.read(), args.device_id, args.start, args.end, args.channel
    )

    # Print the generated subscription for your own debugging
    # Attackers will NOT have access to the output of this (although they may have
    # subscriptions in certain scenarios), but feel free to remove
    #
    # NOTE: Printing sensitive data is generally not good security practice
    logger.debug(f"Generated subscription: {subscription}")

    # Open the file, erroring if the file exists unless the --force arg is provided
    with open(args.subscription_file, "wb" if args.force else "xb") as f:
        f.write(subscription)

    # For your own debugging. Feel free to remove
    logger.success(f"Wrote subscription to {str(args.subscription_file.absolute())}")


if __name__ == "__main__":
    main()
